version: '3.7'
services:
    tomcat:
     container_name: blog_tomcat
     restart: always
     environment:
      TZ: 'Asia/Seoul'
     build:
      context: .
      args:
       warpath: ./war/ROOT.war
       dockerfile: ./Dockerfile
     ports:
      - '80:8080'
      - '443:8443'
     volumes:
      - ./tomcatVol/logs/:/usr/local/tomcat/logs/
      - ./imageVol/upload/:/usr/local/tomcat/webapps/upload/
      - ./tomcatVol/conf/server.xml:/usr/local/tomcat/conf/server.xml    
      - ./tomcatVol/conf/web.xml:/usr/local/tomcat/conf/web.xml
      - ./tomcatVol/conf/keystore.p12:/usr/local/tomcat/conf/keystore.p12

